### ISSUE TITLE
Newbie doubts...

### ISSUE THREAD

**Issue by hribeir0** [paulgreg/thermomix-recipes#2]
Could you please provide some more info on installation? I am comfortable only with php and can't quite grasp how to use you app. Thank you so much

**Comment by paulgreg** [comment]
Once you’ve built it (by running `rake`), you’ll just have to copy the content of the `dist` directory on your webserver.

**Comment by hribeir0** [comment]
I've cloned via git and then ran rake. I've got:

> Cleaning...
Copying files...
Inserting commit info in index.html
Concatening and minifying JS files
Removing non minified css/js files
rake aborted!
Errno::ENOENT: No such file or directory @ unlink_internal - dist/js/thermomix-recipes.js
/root/thermomix-recipes/rakefile.rb:28:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
[root@hribeiro-back thermomix-recipes]# rake --trace
** Invoke default (first_time)
** Execute default
Cleaning...
Copying files...
Inserting commit info in index.html
Concatening and minifying JS files
Removing non minified css/js files
rake aborted!
Errno::ENOENT: No such file or directory @ unlink_internal - dist/js/thermomix-recipes.js
/usr/local/lib/ruby/2.1.0/fileutils.rb:1454:in `unlink'
/usr/local/lib/ruby/2.1.0/fileutils.rb:1454:in `block in remove_file'
/usr/local/lib/ruby/2.1.0/fileutils.rb:1459:in `platform_support'
/usr/local/lib/ruby/2.1.0/fileutils.rb:1453:in `remove_file'
/usr/local/lib/ruby/2.1.0/fileutils.rb:791:in `remove_file'
/usr/local/lib/ruby/2.1.0/fileutils.rb:569:in `block in rm'
/usr/local/lib/ruby/2.1.0/fileutils.rb:568:in `each'
/usr/local/lib/ruby/2.1.0/fileutils.rb:568:in `rm'
/root/thermomix-recipes/rakefile.rb:28:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => default

> 
Despite that I copied dist files but it was not working. What am I doing wrong? Thank you!

**Comment by paulgreg** [comment]
The first `rake` crashed because it tried to remove a non existant file. Fixed in https://github.com/paulgreg/thermomix-recipes/commit/bd46cb42e141c9fce10de7d0338983d6f16af049
I also found a flaky test fixed by https://github.com/paulgreg/thermomix-recipes/commit/820e3124d26673b74ffee3fade54f85ad15617a6.
Please try to `git pull` and retry the `rake` command.

**Comment by hribeir0** [comment]
I've tried and got the same result. I mean, "Build done" but when I access the dist files (index.html) the application is not working. I'm not sure if I'm doing something wrong but it seems I will be unable to get it to work, unfortunately

**Comment by paulgreg** [comment]
Have you copied the content of the `dist` folder into your web server ?
It won’t work if you open directly the page from your file explorer.
Can you tell me more about what is not working ?
What is the error message in your browser (F12 > console) ?

**Comment by hribeir0** [comment]
Yes I have. When I access it via browser http://my-ip/dist I get the html page unformated. No css and all app options on the same page. Plain html..
Checking console:
Failed to load resource: the server responded with a status of 404 (Not Found) concerning thermomix-recipes.min.js and l10n.ini. And also: service worker registration failure: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by paulgreg** [comment]
Can you access to JS / CSS files ? Like http://my-ip/dist/css/thermomix.css or  http://my-ip/dist/js/thermomix-recipes.min.js ?
If not, are they present in CSS or JS directory ?
If they are, it may be a directory permissions problem.
The serviceworker need indeed an HTTPS connection but it’s only to make it work offline.

**Comment by hribeir0** [comment]
So, the strange thing is JS is not a directory..Thermomix.css it's there alright.
Dumb question: would your thermomix-recipes.min.js work on my server?

Indeed, I do not have https setup at this stage. I've been playing with several VPS templates. At this moment it's ubuntu 16.04

**Comment by paulgreg** [comment]
It’s very strange that `js` is not a directory.

I’ve just published a release here : https://github.com/paulgreg/thermomix-recipes/releases/download/untagged-821e8c24c08969d952bd/thermomix-recipes.zip
You can simply unzip that on a directory into your web server. That will exclude any problem during build.

JavaScript is not running on your server but on your browser.
However, you will need PHP support on your server, to load and save data.
But the home page should load, even it PHP is not supported.

**Comment by hribeir0** [comment]
Well thank you. It's a step up but the homepage didn't load. Here's the console info:
```
thermomix-recipes.min.js:10 App.loadData Object
(anonymous) @ thermomix-recipes.min.js:10
80.211.150.50/:332 service worker registration failure: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
thermomix-recipes.min.js:9 Uncaught TypeError: Cannot read property 'map' of undefined
    at Function.x.map.x.collect (thermomix-recipes.min.js:9)
    at Function.x.sortBy (thermomix-recipes.min.js:9)
    at e (thermomix-recipes.min.js:10)
    at Object.a.categories.render (thermomix-recipes.min.js:10)
    at HTMLDivElement.<anonymous> (thermomix-recipes.min.js:10)
    at HTMLDocument.dispatch (thermomix-recipes.min.js:4)
    at HTMLDocument.h (thermomix-recipes.min.js:4)
    at Object.trigger (thermomix-recipes.min.js:4)
    at HTMLDivElement.<anonymous> (thermomix-recipes.min.js:4)
    at Function.each (thermomix-recipes.min.js:3)
```
I do have PHP installed and working.

**Comment by paulgreg** [comment]
Can you try if the resource serving the data is responding ?
Try to access the datastore like that : http://server/thermomix-recipes/datastore.php?n=default
replace the server and the path according where you’ve installed it.

**Comment by hribeir0** [comment]
I get "404 Document not found" Should exist any json file on the data directory?

**Comment by paulgreg** [comment]
Yes, so PHP seems to work.
But I don’t understand the problem above.
Do you mind contacting me in private (my email is on https://paulgreg.me/ or DM me on twitter @paulgreg) so you may send me the link to your instance to inspect it ?
