### ISSUE TITLE
how does this work ?

### ISSUE THREAD

**Issue by sokoow** [paulgreg/thermomix-recipes#3]
Hey Paul, really nice project ;) When I self-host this, is it possible for me to somehow plug this directly into thermomix ? So, is there any way that portals like these are seen as step-by-step instructions on thermomixe's screen ? 

Do you have a dockerfile yet ? :) Greetings

**Comment by paulgreg** [comment]
Hello,

No, to my knowledge, it’s not possible to interact directly with thermomix.

That web application is a « simple » app to store recipes.
You can try it here : http://thermomix.recipes.free.fr (read-only, you won’t be able to save).
I usually use my phone while cooking :-)

I’ll try to create a Dockerfile to simplify installation. Thanks for the idea.

**Comment by paulgreg** [comment]
I’ve added a docker-compose to launch thermomix-recipes from official nginx and php images. 
See [README.docker.md](https://github.com/paulgreg/thermomix-recipes/blob/master/README.docker.md) for further information.
